// Generated by gencpp from file tracking_msgs/WaypointState.msg
// DO NOT EDIT!


#ifndef TRACKING_MSGS_MESSAGE_WAYPOINTSTATE_H
#define TRACKING_MSGS_MESSAGE_WAYPOINTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tracking_msgs
{
template <class ContainerAllocator>
struct WaypointState_
{
  typedef WaypointState_<ContainerAllocator> Type;

  WaypointState_()
    : aid(0)
    , lanechange_state(0)
    , steering_state(0)
    , accel_state(0)
    , stop_state(0)
    , event_state(0)  {
    }
  WaypointState_(const ContainerAllocator& _alloc)
    : aid(0)
    , lanechange_state(0)
    , steering_state(0)
    , accel_state(0)
    , stop_state(0)
    , event_state(0)  {
  (void)_alloc;
    }



   typedef int32_t _aid_type;
  _aid_type aid;

   typedef uint8_t _lanechange_state_type;
  _lanechange_state_type lanechange_state;

   typedef uint8_t _steering_state_type;
  _steering_state_type steering_state;

   typedef uint8_t _accel_state_type;
  _accel_state_type accel_state;

   typedef uint8_t _stop_state_type;
  _stop_state_type stop_state;

   typedef uint8_t _event_state_type;
  _event_state_type event_state;



  enum {
    NULLSTATE = 0u,
    STR_LEFT = 1u,
    STR_RIGHT = 2u,
    STR_STRAIGHT = 3u,
    STR_BACK = 4u,
    TYPE_STOPLINE = 1u,
    TYPE_STOP = 2u,
    TYPE_EVENT_NULL = 0u,
    TYPE_EVENT_GOAL = 1u,
    TYPE_EVENT_MIDDLE_GOAL = 2u,
    TYPE_EVENT_POSITION_STOP = 3u,
    TYPE_EVENT_BUS_STOP = 4u,
    TYPE_EVENT_PARKING = 5u,
  };


  typedef boost::shared_ptr< ::tracking_msgs::WaypointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tracking_msgs::WaypointState_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointState_

typedef ::tracking_msgs::WaypointState_<std::allocator<void> > WaypointState;

typedef boost::shared_ptr< ::tracking_msgs::WaypointState > WaypointStatePtr;
typedef boost::shared_ptr< ::tracking_msgs::WaypointState const> WaypointStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tracking_msgs::WaypointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tracking_msgs::WaypointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tracking_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'tracking_msgs': ['/home/jing/combine_ws/src/tracking_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tracking_msgs::WaypointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracking_msgs::WaypointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracking_msgs::WaypointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracking_msgs::WaypointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracking_msgs::WaypointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracking_msgs::WaypointState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tracking_msgs::WaypointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "623a0ffbb0a052490adc981c2a3e8edd";
  }

  static const char* value(const ::tracking_msgs::WaypointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x623a0ffbb0a05249ULL;
  static const uint64_t static_value2 = 0x0adc981c2a3e8eddULL;
};

template<class ContainerAllocator>
struct DataType< ::tracking_msgs::WaypointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tracking_msgs/WaypointState";
  }

  static const char* value(const ::tracking_msgs::WaypointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tracking_msgs::WaypointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 aid\n\
uint8 NULLSTATE=0\n\
\n\
# lanechange\n\
uint8 lanechange_state\n\
\n\
# bilinker\n\
uint8 steering_state\n\
uint8 STR_LEFT=1\n\
uint8 STR_RIGHT=2\n\
uint8 STR_STRAIGHT=3\n\
uint8 STR_BACK=4\n\
\n\
uint8 accel_state\n\
\n\
uint8 stop_state\n\
# 1 is stopline, 2 is stop which can only be released manually.\n\
uint8 TYPE_STOPLINE=1\n\
uint8 TYPE_STOP=2\n\
\n\
uint8 event_state\n\
uint8 TYPE_EVENT_NULL = 0\n\
uint8 TYPE_EVENT_GOAL = 1\n\
uint8 TYPE_EVENT_MIDDLE_GOAL = 2\n\
uint8 TYPE_EVENT_POSITION_STOP = 3\n\
uint8 TYPE_EVENT_BUS_STOP = 4\n\
uint8 TYPE_EVENT_PARKING = 5\n\
";
  }

  static const char* value(const ::tracking_msgs::WaypointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tracking_msgs::WaypointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.aid);
      stream.next(m.lanechange_state);
      stream.next(m.steering_state);
      stream.next(m.accel_state);
      stream.next(m.stop_state);
      stream.next(m.event_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tracking_msgs::WaypointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tracking_msgs::WaypointState_<ContainerAllocator>& v)
  {
    s << indent << "aid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.aid);
    s << indent << "lanechange_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lanechange_state);
    s << indent << "steering_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.steering_state);
    s << indent << "accel_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accel_state);
    s << indent << "stop_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop_state);
    s << indent << "event_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.event_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACKING_MSGS_MESSAGE_WAYPOINTSTATE_H
