// Generated by gencpp from file lidar_msgs/ObjectData.msg
// DO NOT EDIT!


#ifndef LIDAR_MSGS_MESSAGE_OBJECTDATA_H
#define LIDAR_MSGS_MESSAGE_OBJECTDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <lidar_msgs/Object.h>

namespace lidar_msgs
{
template <class ContainerAllocator>
struct ObjectData_
{
  typedef ObjectData_<ContainerAllocator> Type;

  ObjectData_()
    : header()
    , bbox()
    , token()  {
    }
  ObjectData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bbox(_alloc)
    , token(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::lidar_msgs::Object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lidar_msgs::Object_<ContainerAllocator> >::other >  _bbox_type;
  _bbox_type bbox;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _token_type;
  _token_type token;





  typedef boost::shared_ptr< ::lidar_msgs::ObjectData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_msgs::ObjectData_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectData_

typedef ::lidar_msgs::ObjectData_<std::allocator<void> > ObjectData;

typedef boost::shared_ptr< ::lidar_msgs::ObjectData > ObjectDataPtr;
typedef boost::shared_ptr< ::lidar_msgs::ObjectData const> ObjectDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_msgs::ObjectData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_msgs::ObjectData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidar_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lidar_msgs': ['/home/jing/combine_ws/src/lidar_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidar_msgs::ObjectData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_msgs::ObjectData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_msgs::ObjectData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_msgs::ObjectData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_msgs::ObjectData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_msgs::ObjectData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_msgs::ObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cce2fe89002b3c1acf48988217c33108";
  }

  static const char* value(const ::lidar_msgs::ObjectData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcce2fe89002b3c1aULL;
  static const uint64_t static_value2 = 0xcf48988217c33108ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_msgs::ObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_msgs/ObjectData";
  }

  static const char* value(const ::lidar_msgs::ObjectData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_msgs::ObjectData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
Object[] bbox\n\
string token\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: lidar_msgs/Object\n\
\n\
Point3 center\n\
Point3 size\n\
Point2 velocity\n\
Point2[] corners\n\
Point2[] contours\n\
int16 id\n\
\n\
float64[36] predict_covariance\n\
\n\
\n\
\n\
================================================================================\n\
MSG: lidar_msgs/Point3\n\
float32 x\n\
float32 y\n\
float32 z\n\
================================================================================\n\
MSG: lidar_msgs/Point2\n\
float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::lidar_msgs::ObjectData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_msgs::ObjectData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bbox);
      stream.next(m.token);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_msgs::ObjectData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_msgs::ObjectData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bbox[]" << std::endl;
    for (size_t i = 0; i < v.bbox.size(); ++i)
    {
      s << indent << "  bbox[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidar_msgs::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.bbox[i]);
    }
    s << indent << "token: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.token);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_MSGS_MESSAGE_OBJECTDATA_H
